/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sanya' at '12.09.16 9:41' with Gradle 2.4
 *
 * @author Sanya, @date 12.09.16 9:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
